### ISSUE TITLE
[BUG]: get PlatformException and Crash when called startPlayer

### ISSUE THREAD

**Issue by unclexiao** [Canardoux/tau#644]
## Flutter Sound Version : 7.7.0+1

- **FULL** or **LITE** flavor ? LITE

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```
```
|-- flutter_sound 7.7.0+1
|   |-- flutter_sound_platform_interface 7.7.0+1
|   |-- flutter_sound_web 7.7.0+1
|   |   |-- flutter_sound_platform_interface...
```
----------------------------------------------------------

## Severity

- Crash ? YES

- Result is not what expected ? YES

- Cannot build my App ? NO

- Minor issue ? NO

--------------------------------------------------------

## Platforms you faced the error 
- Android 

------------------------------------------------

**Describe the bug**
I recorded my sound with ``flutter_audio_recorder``, and upload to my server. Then I try to call ``startPlayer`` , it stuck , and a few seconds later, it crash! 

**To Reproduce**
1. Record my sound : 
```dart
 _recorder = FlutterAudioRecorder(tempPath,
          audioFormat: AudioFormat.AAC);
      await _recorder.initialized;
      await _recorder.start();
```
2. Upload to server and get this [url](http://rongcloud-audio.ronghub.com/audio_amr__RC-2021-03-09_129_1615304167092.aac?e=1630856169&token=livk5rb3__JZjCtEiMxXpQ8QscLxbNLehwhHySnX:LxZAFvCKBVd4qECJRfQ5MdG_Yyg=)
3. Try to play[ the remote url](http://rongcloud-audio.ronghub.com/audio_amr__RC-2021-03-09_129_1615304167092.aac?e=1630856169&token=livk5rb3__JZjCtEiMxXpQ8QscLxbNLehwhHySnX:LxZAFvCKBVd4qECJRfQ5MdG_Yyg=)
```dart
 FlutterSoundPlayer().openAudioSession().then((FlutterSoundPlayer player) {
      player.setSubscriptionDuration(const Duration(seconds: 1));
      player.startPlayer(
        fromURI: path,
        codec: Codec.aacADTS,
        whenFinished: () {
          print('I hope you enjoyed listening to this song');
        },
      );
      player.onProgress.listen((PlaybackDisposition pos) {
        print('${pos.position}/${pos.duration}');
      });
    }, onError: (dynamic err) {
      print('error');
    });
```
4. Got  **stuck** , and  **crash**

----------------------------------------------

# Logs!!!!
(**This is very important**. Most of the time we cannot do anything if we do not have information on your bug)
```
I/flutter ( 5765): FS:---> openAudioSession
I/flutter ( 5765): Resetting flutter_sound Player Plugin
I/AudioManager( 5765): In stopBluetoothSco(), calling application: com.jinqikeji.cygnus_app_hybrid
I/AudioManager( 5765): In setBluetoothScoOn(), on: false, calling application: com.jinqikeji.cygnus_app_hybrid
I/AudioManager( 5765): In setSpeakerphoneOn(), on: true, calling application: com.jinqikeji.cygnus_app_hybrid
I/AudioManager( 5765): In setSpeakerphoneOn(), on: true, calling application: com.jinqikeji.cygnus_app_hybrid
I/AudioManager( 5765): In setBluetoothScoOn(), on: false, calling application: com.jinqikeji.cygnus_app_hybrid
I/AudioManager( 5765): In stopBluetoothSco(), calling application: com.jinqikeji.cygnus_app_hybrid
I/flutter ( 5765): FS:---> channelMethodCallHandler : openPlayerCompleted
D/AudioManager( 5765): getStreamVolume isRestricted mode = 0
I/flutter ( 5765): ---> openPlayerCompleted: true
I/flutter ( 5765): <--- openPlayerCompleted: true
I/flutter ( 5765): FS:<--- channelMethodCallHandler : openPlayerCompleted
I/flutter ( 5765): FS:<--- openAudioSession
D/AudioManager( 5765): getStreamVolume isRestricted mode = 0
I/chatty  ( 5765): uid=10686(com.jinqikeji.cygnus_app_hybrid) identical 4 lines
D/AudioManager( 5765): getStreamVolume isRestricted mode = 0
D/AudioManager( 5765): getStreamVolume isRestricted mode = 0
I/chatty  ( 5765): uid=10686(com.jinqikeji.cygnus_app_hybrid) identical 20 lines
D/AudioManager( 5765): getStreamVolume isRestricted mode = 0
I/flutter ( 5765): FS:---> setSubscriptionDuration
I/flutter ( 5765): FS:---> startPlayer
I/flutter ( 5765): FS:---> stop
I/flutter ( 5765): FS:<---- setSubscriptionDuration
I/flutter ( 5765): ---> stopPlayerCompleted: true
I/flutter ( 5765): <--- stopPlayerCompleted: true
I/flutter ( 5765): FS:<--- stop
I/flutter ( 5765): FS:---> _convert
I/flutter ( 5765): FS:---> needToConvert
I/flutter ( 5765): FS:<--- needToConvert
I/flutter ( 5765): FS:<--- _convert
V/MediaHTTPService( 5765): MediaHTTPService(android.media.MediaHTTPService@b02e254): Cookies: null
V/MediaHTTPService( 5765): makeHTTPConnection: CookieManager created: java.net.CookieManager@22825fd
V/MediaHTTPService( 5765): makeHTTPConnection(android.media.MediaHTTPService@b02e254): cookieHandler: java.net.CookieManager@22825fd Cookies: null
E/MediaPlayerNative( 5765): error (1, -2147483648)
E/FlautoPlayer( 5765): startPlayer() exception
E/flutter ( 5765): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, startPlayer() error, null)
[38;5;244mE/flutter ( 5765): #0      StandardMethodCodec.decodeEnvelope[39;49m
 package:flutter/…/services/message_codecs.dart
[38;5;244mE/flutter ( 5765): #1      MethodChannel._invokeMethod[39;49m
 package:flutter/…/services/platform_channel.dart
E/flutter ( 5765): <asynchronous suspension>
[38;5;244mE/flutter ( 5765): #2      MethodChannel.invokeMethod[39;49m
 package:flutter/…/services/platform_channel.dart
[38;5;248mE/flutter ( 5765): #3      MethodChannelFlutterSoundPlayer.invokeMethod[39;49m
 package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart
[38;5;248mE/flutter ( 5765): #4      MethodChannelFlutterSoundPlayer.startPlayer[39;49m
 package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart
[38;5;248mE/flutter ( 5765): #5      FlutterSoundPlayer._startPlayer[39;49m
 package:flutter_sound/public/flutter_sound_player.dart
E/flutter ( 5765): <asynchronous suspension>
[38;5;248mE/flutter ( 5765): #6      FlutterSoundPlayer.startPlayer.<anonymous closure>[39;49m
 package:flutter_sound/public/flutter_sound_player.dart
[38;5;248mE/flutter ( 5765): #7      BasicLock.synchronized[39;49m
 package:synchronized/src/basic_lock.dart
[38;5;248mE/flutter ( 5765): #8      FlutterSoundPlayer.startPlayer[39;49m
 package:flutter_sound/public/flutter_sound_player.dart
[38;5;248mE/flutter ( 5765): #9      MediaService.startPlayAudio.<anonymous closure>[39;49m
 package:cygnus_app_hybrid/service/media.dart
[38;5;244mE/flutter ( 5765): #10     _rootRunUnary (dart:async/zone.dart:1198:47)[39;49m
[38;5;244mE/flutter ( 5765): #11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)[39;49m
[38;5;244mE/flutter ( 5765): #12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)[39;49m
[38;5;244mE/flutter ( 5765): #13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)[39;49m
[38;5;244mE/flutter ( 5765): #14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)[39;49m
[38;5;244mE/flutter ( 5765): #15     Future._completeWithValue (dart:async/future_impl.dart:529:5)[39;49m
[38;5;244mE/flutter ( 5765): #16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)[39;49m
[38;5;244mE/flutter ( 5765): #17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)[39;49m
[38;5;248mE/flutter ( 5765): #18     FlutterSoundPlayer.openAudioSession (package:flutter_sound/public/flutter_sound_player.dart)[39;49m
 package:flutter_sound/public/flutter_sound_player.dart
[38;5;244mE/flutter ( 5765): #19     _rootRunUnary (dart:async/zone.dart:1198:47)[39;49m
[38;5;244mE/flutter ( 5765): #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)[39;49m
[38;5;244mE/flutter ( 5765): #21     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)[39;49m
[38;5;244mE/flutter ( 5765): #22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)[39;49m
[38;5;244mE/flutter ( 5765): #23     Future._propagateToListeners (dart:async/future_impl.dart:725:32)[39;49m
[38;5;244mE/flutter ( 5765): #24     Future._completeWithValue (dart:async/future_impl.dart:529:5)[39;49m
[38;5;244mE/flutter ( 5765): #25     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)[39;49m
[38;5;244mE/flutter ( 5765): #26     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)[39;49m
[38;5;248mE/flutter ( 5765): #27     BasicLock.synchronized (package:synchronized/src/basic_lock.dart)[39;49m
 package:synchronized/src/basic_lock.dart
[38;5;244mE/flutter ( 5765): #28     _rootRunUnary (dart:async/zone.dart:1198:47)[39;49m
[38;5;244mE/flutter ( 5765): #29     _CustomZone.runUnary (dart:async/zone.dart:1100:19)[39;49m
[38;5;244mE/flutter ( 5765): #30     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)[39;49m
[38;5;244mE/flutter ( 5765): #31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)[39;49m
[38;5;244mE/flutter ( 5765): #32     Future._propagateToListeners (dart:async/future_impl.dart:725:32)[39;49m
[38;5;244mE/flutter ( 5765): #33     Future._completeWithValue (dart:async/future_impl.dart:529:5)[39;49m
[38;5;244mE/flutter ( 5765): #34     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)[39;49m
[38;5;244mE/flutter ( 5765): #35     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)[39;49m
[38;5;248mE/flutter ( 5765): #36     FlutterSoundPlayer.openAudioSession.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart)[39;49m
 package:flutter_sound/public/flutter_sound_player.dart
[38;5;244mE/flutter ( 5765): #37     _rootRunUnary (dart:async/zone.dart:1198:47)[39;49m
[38;5;244mE/flutter ( 5765): #38     _CustomZone.runUnary (dart:async/zone.dart:1100:19)[39;49m
[38;5;244mE/flutter ( 5765): #39     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)[39;49m
[38;5;244mE/flutter ( 5765): #40     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)[39;49m
[38;5;244mE/flutter ( 5765): #41     Future._propagateToListeners (dart:async/future_impl.dart:725:32)[39;49m
[38;5;244mE/flutter ( 5765): #42     Future._chainCoreFuture (dart:async/future_impl.dart:496:7)[39;49m
[38;5;244mE/flutter ( 5765): #43     Future._chainFuture (dart:async/future_impl.dart:580:9)[39;49m
[38;5;244mE/flutter ( 5765): #44     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:37:15)[39;49m
[38;5;244mE/flutter ( 5765): #45     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)[39;49m
E/flutter ( 5765): #46     FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart
```
-----------------------------------------------------------------

**Comment by Larpoux** [comment]
- The file on your server is a _Wave_ file. Not _AAC_.
- The file is a blank record during 2 seconds.

**Comment by unclexiao** [comment]
I removed `flutter_audio_recorder` ,and call `openAudioSession` . Finally, it worked.

**Comment by Larpoux** [comment]
Good news 😄
