### ISSUE TITLE
[BUG]: Dynamic call with too few arguments on Flutter Web

### ISSUE THREAD

**Issue by tbarbette** [Canardoux/tau#672]
## Flutter Sound Version : 

- **FULL** or **LITE** flavor ?
No idea, just followed the guide for Flutter.

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```
```
|-- flutter_sound 8.1.1
|   |-- flutter...
|   |-- flutter_sound_platform_interface 8.1.1
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- flutter_sound_web 8.1.1
|   |   |-- flutter...
|   |   |-- flutter_sound_platform_interface...
|   |   |-- flutter_web_plugins...
```

----------------------------------------------------------

## Severity

Sound does not work

--------------------------------------------------------

## Platforms you faced the error 

- Flutter Web ?

------------------------------------------------

**Describe the bug**

The sound does not start and I got this error. I did add the JS lines as in the doc at https://tau.canardoux.xyz/guides_web.html

```
FS:---> openAudioSession
Resetting flutter_sound Player Plugin
---> resetPlugin
<--- resetPlugin
Error: NoSuchMethodError: ''
Dynamic call with too few arguments. Expected: 3 Actual: 2
Receiver: Instance of '(FlutterSoundPlayerCallback, int, int) => Null'
Arguments: [Instance of 'FlutterSoundPlayer', true]
    at Object.throw_ [as throw] (http://localhost:63640/dart_sdk.js:5333:11)
    at Object.defaultNoSuchMethod (http://localhost:63640/dart_sdk.js:5778:15)
    at Function.noSuchMethod (http://localhost:63640/dart_sdk.js:6878:19)
    at Object.noSuchMethod (http://localhost:63640/dart_sdk.js:5774:30)
    at callNSM (http://localhost:63640/dart_sdk.js:5506:19)
    at Object._checkAndCall (http://localhost:63640/dart_sdk.js:5545:12)
    at Object.dcall (http://localhost:63640/dart_sdk.js:5548:17)
    at Array.ret (http://localhost:63640/dart_sdk.js:60992:21)
    at FlutterSoundPlayer.initializeMediaPlayer (https://cdn.jsdelivr.net/npm/tau_sound_core@7.4.13/js/flutter_sound/flutter_sound_player.min.js:7:630)
    at flutter_sound_player_web.FlutterSoundPlayerWeb.new.openPlayer (http://localhost:63640/packages/flutter_sound_web/flutter_sound_player_web.dart.lib.js:90:60)
    at openPlayer.next (<anonymous>)
    at runBody (http://localhost:63640/dart_sdk.js:39051:34)
    at Object._async [as async] (http://localhost:63640/dart_sdk.js:39082:7)
    at flutter_sound_player_web.FlutterSoundPlayerWeb.new.openPlayer (http://localhost:63640/packages/flutter_sound_web/flutter_sound_player_web.dart.lib.js:81:20)
    at flutter_sound_player.FlutterSoundPlayer.new._openAudioSession (http://localhost:63640/packages/flutter_sound/public/ui/sound_recorder_ui.dart.lib.js:5134:106)
    at _openAudioSession.next (<anonymous>)
    at http://localhost:63640/dart_sdk.js:39031:33
    at _RootZone.runUnary (http://localhost:63640/dart_sdk.js:38888:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:63640/dart_sdk.js:33874:29)
    at handleValueCallback (http://localhost:63640/dart_sdk.js:34434:49)
    at Function._propagateToListeners (http://localhost:63640/dart_sdk.js:34472:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:63640/dart_sdk.js:34190:27)
    at Object._microtaskLoop (http://localhost:63640/dart_sdk.js:39175:13)
    at _startMicrotaskLoop (http://localhost:63640/dart_sdk.js:39181:13)
    at http://localhost:63640/dart_sdk.js:34688:9
```

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
hi @tbarbette ,

It looks like there is something wrong with Flutter Sound on Web. I am going to look to your Problem Report now.
I will give you some news this evening.

**Comment by Larpoux** [comment]
@tbarbette ,

Can you check that the JS scripts that you import into your .html file have the correct version : 8.1.1 ?
I am wondering if you downloaded a previous version of flutter_sound_player.js  and you still use it with 8.1.1 as static includes.

**Comment by tbarbette** [comment]
I have this as per the documentation : 
```
  <script src="assets/packages/flutter_sound_web/js/flutter_sound/flutter_sound.js"></script>
  <script src="assets/packages/flutter_sound_web/js/flutter_sound/flutter_sound_player.js"></script>
  <script src="assets/packages/flutter_sound_web/js/flutter_sound/flutter_sound_recorder.js"></script>
  <script src="assets/packages/flutter_sound_web/js/howler/howler.js"></script>
```
And before that I copy-pasted some similar lines from an issue. That I removed. Maybe those stated in cache then indeed?

**Comment by Larpoux** [comment]
Yes, this is the problem.

Actually you import Javascript files from the assets/packages/ directory, but those files are old, and not good with the current versions. 

You must 
- either download the correct JS files, 
- or use dynamically the last Javascript files published.
Both alternatives have good points and bad points.

you should refer to the Installation Notice on the flutter Sound documentation.

**Comment by tbarbette** [comment]
I refered to that ( https://tau.canardoux.xyz/guides_web.html ) which does not say why static could be a bad idea :) I'd suggest to add a sentence there, but this is not really a bug so I'll close.
