### ISSUE TITLE
crash App in release mode, throw Bad JNI version returned from JNI_OnLoad[HELP]:

### ISSUE THREAD

**Issue by anypwx** [Canardoux/tau#749]
Description:
that app normal run in debug mode, but crash app  run in release mode

Excetoption:
E/AndroidRuntime(19710): Process: com.xxx.xxx.xxx, PID: 19710
E/AndroidRuntime(19710): java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/com.xxx.xxx.xxx-1LzGhct7XNXtmrMtKMcCeA==/base.apk!/lib/arm64-v8a/libmobileffmpeg.so": 0
E/AndroidRuntime(19710): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
E/AndroidRuntime(19710): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/AndroidRuntime(19710): 	at java.lang.System.loadLibrary(System.java:1668)
E/AndroidRuntime(19710): 	at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:19)
E/AndroidRuntime(19710): 	at com.arthenica.mobileffmpeg.Config.c(Unknown Source:0)
E/AndroidRuntime(19710): 	at c.b.a.e.onMethodCall(FlutterSoundFFmpeg.java:35)
E/AndroidRuntime(19710): 	at d.a.c.a.k$a.a(MethodChannel.java:2)
E/AndroidRuntime(19710): 	at io.flutter.embedding.engine.dart.a.e(DartMessenger.java:5)
E/AndroidRuntime(19710): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:2)
E/AndroidRuntime(19710): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(19710): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/AndroidRuntime(19710): 	at android.os.Looper.loop(Looper.java:173)
E/AndroidRuntime(19710): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/AndroidRuntime(19710): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19710): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(19710): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

app gradle config:
defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.xxx.xxx.xxx"
        minSdkVersion 24
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

flutter :
 • Flutter version 2.2.3 at D:\xx
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

dependencies:
flutter_sound: ^8.3.9

**Comment by anypwx** [comment]
find it solved this issure been resolved   https://github.com/tanersener/flutter-ffmpeg/issues/237
