### ISSUE TITLE
Unable to record on iOS

### ISSUE THREAD

**Issue by yanivshaked** [Canardoux/tau#9]
Using the provided example, I'm trying to record audio on iOS. After the example application is running, I'm clicking on `simpleRecorder` and then on `GO` button, and getting the following error message:
```
Unhandled Exception: Instance of 'RecordingPermissionException'
#0      _SimpleRecorderState.openTheRecorder (package:example/simple_recorder/simple_recorder.dart:104:9)
```
<details>
  <summary>Full log is here</summary>

```

twelve@Twelves-Mac-mini example % flutter run                                                 
Launching lib/main.dart on Dev’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: XPWXU59S64
Running pod install...                                           1,281ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         3.1s
Xcode build done.                                            9.0s
Installing and launching...                                        14.4s
Error: unable to find directory entry in pubspec.yaml: /Users/twelve/Development/tau/tau_sound/example/assets/extract/
Syncing files to device Dev’s iPhone...                             84ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Dev’s iPhone is available at: http://127.0.0.1:65225/bVN7o42FGsU=/
The Flutter DevTools debugger and profiler on Dev’s iPhone is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:65225/bVN7o42FGsU=/
2021-11-04 14:30:57.406092+0200 Flutter Sound Example[2260:1983239] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.406257+0200 Flutter Sound Example[2260:1983239] flutter: │ #0   new TauPlayer (package:tau_sound_lite/public/tau_player.dart:110:13)
2021-11-04 14:30:57.406390+0200 Flutter Sound Example[2260:1983239] flutter: │ #1   new _SimpleRecorderState (package:example/simple_recorder/simple_recorder.dart:63:25)
2021-11-04 14:30:57.406452+0200 Flutter Sound Example[2260:1983239] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-11-04 14:30:57.406516+0200 Flutter Sound Example[2260:1983239] flutter: │ 🐛 ctor: TauPlayer()
2021-11-04 14:30:57.407329+0200 Flutter Sound Example[2260:1983239] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.415008+0200 Flutter Sound Example[2260:1983239] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.415154+0200 Flutter Sound Example[2260:1983239] flutter: │ #0   new TauRecorder (package:tau_sound_lite/public/tau_recorder.dart:108:13)
2021-11-04 14:30:57.415241+0200 Flutter Sound Example[2260:1983239] flutter: │ #1   new _SimpleRecorderState (package:example/simple_recorder/simple_recorder.dart:64:29)
2021-11-04 14:30:57.415333+0200 Flutter Sound Example[2260:1983239] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-11-04 14:30:57.415395+0200 Flutter Sound Example[2260:1983239] flutter: │ 🐛 ctor: TauRecorder()
2021-11-04 14:30:57.415457+0200 Flutter Sound Example[2260:1983239] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.427816+0200 Flutter Sound Example[2260:1983239] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.428013+0200 Flutter Sound Example[2260:1983239] flutter: │ #0   TauPlayer._open (package:tau_sound_lite/public/tau_player.dart:787:13)
2021-11-04 14:30:57.428073+0200 Flutter Sound Example[2260:1983239] flutter: │ #1   TauPlayer.open.<anonymous closure> (package:tau_sound_lite/public/tau_player.dart:214:17)
2021-11-04 14:30:57.428124+0200 Flutter Sound Example[2260:1983239] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-11-04 14:30:57.428559+0200 Flutter Sound Example[2260:1983239] flutter: │ 🐛 FS:---> open()
2021-11-04 14:30:57.428828+0200 Flutter Sound Example[2260:1983239] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.547477+0200 Flutter Sound Example[2260:1983239] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.547573+0200 Flutter Sound Example[2260:1983239] flutter: │ #0   TauPlayer.log (package:tau_sound_lite/public/tau_player.dart:1856:13)
2021-11-04 14:30:57.547611+0200 Flutter Sound Example[2260:1983239] flutter: │ #1   MethodChannelTauPlayer.channelMethodCallHandler (package:tau_platform_interface/method_channel_tau_player.dart:159:19)
2021-11-04 14:30:57.547648+0200 Flutter Sound Example[2260:1983239] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-11-04 14:30:57.550421+0200 Flutter Sound Example[2260:1983239] flutter: │ 🐛 IOS:--> initializeFlautoPlayer
2021-11-04 14:30:57.550464+0200 Flutter Sound Example[2260:1983239] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.552088+0200 Flutter Sound Example[2260:1983239] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.552153+0200 Flutter Sound Example[2260:1983239] flutter: │ #0   TauPlayer.log (package:tau_sound_lite/public/tau_player.dart:1856:13)
2021-11-04 14:30:57.552185+0200 Flutter Sound Example[2260:1983239] flutter: │ #1   MethodChannelTauPlayer.channelMethodCallHandler (package:tau_platform_interface/method_channel_tau_player.dart:159:19)
2021-11-04 14:30:57.552219+0200 Flutter Sound Example[2260:1983239] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-11-04 14:30:57.558933+0200 Flutter Sound Example[2260:1983239] flutter: │ 🐛 IOS:--> initializeFlautoPlayer
2021-11-04 14:30:57.558987+0200 Flutter Sound Example[2260:1983239] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.559781+0200 Flutter Sound Example[2260:1983239] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.559869+0200 Flutter Sound Example[2260:1983239] flutter: │ #0   TauPlayer.log (package:tau_sound_lite/public/tau_player.dart:1856:13)
2021-11-04 14:30:57.559909+0200 Flutter Sound Example[2260:1983239] flutter: │ #1   MethodChannelTauPlayer.channelMethodCallHandler (package:tau_platform_interface/method_channel_tau_player.dart:159:19)
2021-11-04 14:30:57.559951+0200 Flutter Sound Example[2260:1983239] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-11-04 14:30:57.560339+0200 Flutter Sound Example[2260:1983239] flutter: │ 🐛 iOS: invokeMethod openPlayerCompleted - state=0
2021-11-04 14:30:57.560449+0200 Flutter Sound Example[2260:1983239] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.561913+0200 Flutter Sound Example[2260:1983239] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.562345+0200 Flutter Sound Example[2260:1983239] flutter: │ #0   TauPlayer.openPlayerCompleted (package:tau_sound_lite/public/tau_player.dart:1691:13)
2021-11-04 14:30:57.562415+0200 Flutter Sound Example[2260:1983239] flutter: │ #1   MethodChannelTauPlayer.channelMethodCallHandler (package:tau_platform_interface/method_channel_tau_player.dart:118:19)
2021-11-04 14:30:57.562584+0200 Flutter Sound Example[2260:1983239] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-11-04 14:30:57.563025+0200 Flutter Sound Example[2260:1983239] flutter: │ 🐛 ---> openPlayerCompleted: true
2021-11-04 14:30:57.563066+0200 Flutter Sound Example[2260:1983239] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.564347+0200 Flutter Sound Example[2260:1983239] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.564896+0200 Flutter Sound Example[2260:1983239] flutter: │ #0   TauPlayer.openPlayerCompleted (package:tau_sound_lite/public/tau_player.dart:1705:13)
2021-11-04 14:30:57.565159+0200 Flutter Sound Example[2260:1983239] flutter: │ #1   MethodChannelTauPlayer.channelMethodCallHandler (package:tau_platform_interface/method_channel_tau_player.dart:118:19)
2021-11-04 14:30:57.566049+0200 Flutter Sound Example[2260:1983239] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-11-04 14:30:57.566192+0200 Flutter Sound Example[2260:1983239] flutter: │ 🐛 <--- openPlayerCompleted: true
2021-11-04 14:30:57.566228+0200 Flutter Sound Example[2260:1983239] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.567689+0200 Flutter Sound Example[2260:1983239] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.567872+0200 Flutter Sound Example[2260:1983239] flutter: │ #0   TauPlayer.log (package:tau_sound_lite/public/tau_player.dart:1856:13)
2021-11-04 14:30:57.568013+0200 Flutter Sound Example[2260:1983239] flutter: │ #1   MethodChannelTauPlayer.channelMethodCallHandler (package:tau_platform_interface/method_channel_tau_player.dart:159:19)
2021-11-04 14:30:57.570621+0200 Flutter Sound Example[2260:1983239] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-11-04 14:30:57.570676+0200 Flutter Sound Example[2260:1983239] flutter: │ 🐛 IOS:<-- initializeFlautoPlayer
2021-11-04 14:30:57.570710+0200 Flutter Sound Example[2260:1983239] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.571795+0200 Flutter Sound Example[2260:1983239] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.573732+0200 Flutter Sound Example[2260:1983239] flutter: │ #0   TauPlayer._open (package:tau_sound_lite/public/tau_player.dart:833:13)
2021-11-04 14:30:57.573777+0200 Flutter Sound Example[2260:1983239] flutter: │ #1   <asynchronous suspension>
2021-11-04 14:30:57.573812+0200 Flutter Sound Example[2260:1983239] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-11-04 14:30:57.574299+0200 Flutter Sound Example[2260:1983239] flutter: │ 🐛 FS:<--- open()
2021-11-04 14:30:57.574369+0200 Flutter Sound Example[2260:1983239] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.577349+0200 Flutter Sound Example[2260:1983239] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.577429+0200 Flutter Sound Example[2260:1983239] flutter: │ #0   TauPlayer.log (package:tau_sound_lite/public/tau_player.dart:1856:13)
2021-11-04 14:30:57.577461+0200 Flutter Sound Example[2260:1983239] flutter: │ #1   MethodChannelTauPlayer.channelMethodCallHandler (package:tau_platform_interface/method_channel_tau_player.dart:159:19)
2021-11-04 14:30:57.577495+0200 Flutter Sound Example[2260:1983239] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-11-04 14:30:57.579101+0200 Flutter Sound Example[2260:1983239] flutter: │ 🐛 IOS:<-- initializeFlautoPlayer
2021-11-04 14:30:57.579325+0200 Flutter Sound Example[2260:1983239] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-04 14:30:57.583328+0200 Flutter Sound Example[2260:1983239] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Instance of 'RecordingPermissionException'
#0      _SimpleRecorderState.openTheRecorder (package:example/simple_recorder/simple_recorder.dart:104:9)
<asynchronous suspension>

```

  
</details>

**Comment by yanivshaked** [comment]
Problem was missing definitions in `Podfile`, due to using `permission_handler` plugin version 8.2.5.
